/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysmarthome;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author ktams
 */
public class Statistik extends javax.swing.JFrame {

    public byte[] iVal = null;
    public String parentTemp = "";
    String strToday;
    String str100days;
    boolean bShowTemp = false;
    int MouseX, MouseY;
    
    /**
     * Creates new form Statistik
     */
    public Statistik() {
        ImageIcon II = new ImageIcon(getClass().getResource("pictures/Home.jpg"));
        this.setIconImage(II.getImage());
        initComponents();
        strToday =java.util.ResourceBundle.getBundle("mysmarthome/Bundle").getString("today");
        str100days =java.util.ResourceBundle.getBundle("mysmarthome/Bundle").getString("100days");
        this.setResizable(false);
        this.setBounds(50, 50, this.getBounds().width, this.getBounds().height);
    }

    @Override
    public void paint(Graphics g)
    {
        super.paint(g);
        g.drawLine(50, 50, 50, 330);
        g.drawLine(50, 330, 850, 330);
        for( int i = 1; i < 100; i++)
        {
            if((i%20) == 0)
            {
                g.setColor(Color.LIGHT_GRAY);
                g.drawLine(50 + 8*i, 325, 50 + 8*i, 50);
                g.setColor(Color.black);
                g.drawString(""+i, 42 + 8*i, 350);
            }
            g.drawLine(50 + 8*i, 325, 50 + 8*i, 335);
        }
        g.drawString(strToday, 820, 350);
        g.drawString(str100days, 10, 350);
        for( int i = 0; i < 70; i += 5)
        {
            if((i%10) == 0)
            {
                g.setColor(Color.LIGHT_GRAY);
                g.drawLine(45, 50 + i*4, 850, 50 + i*4);
                g.setColor(Color.black);
            }
            g.drawLine(45, 50 + i*4, 55, 50 + i*4);
        }
        g.setColor(Color.LIGHT_GRAY);
        g.drawLine(50, 250, 850, 250);
        g.setColor(Color.black);
        g.drawString("0°C", 20, 255);
        g.drawString("-10°C", 10, 295);
        g.drawString("10°C", 15, 215);
        g.drawString("20°C", 15, 175);
        g.drawString("30°C", 15, 135);
        g.drawString("40°C", 15, 95);
        
        if(iVal != null)
        {
            int xMax = -100, yMax = -100;
            int xMin = 100, yMin = 100;
            
            for(int i = 0; i < iVal.length-1; i++)
            {
                int x1 = iVal[iVal.length - 1 -i];
                if(x1 < xMin)
                {
                    xMin = x1;
                    yMin = i;
                }
                if(x1 > xMax)
                {
                    xMax = x1;
                    yMax = i;
                }
                int x2 = iVal[iVal.length - 2 - i];
                
                g.drawLine(850 - i*8, 250 - x1*4, 850 - (i+1)*8, 250 - x2*4);
            }
            g.setColor(Color.red);
            g.drawLine(850 - yMin*8, 250 - xMin*4, 850 - yMin*8, 240 - xMin*4);
            g.drawString(""+xMin, 840 - yMin*8, 238 - xMin*4);
            g.setColor(Color.green);
            g.drawLine(850 - yMax*8, 250 - xMax*4, 850 - yMax*8, 240 - xMax*4);
            g.drawString(""+xMax, 840 - yMax*8, 238 - xMax*4);
            g.setColor(Color.black);
            if(bShowTemp)
            {
                int x = (MouseX - 50)/8;
                if(x >= 0 && x < 100)
                    g.drawString(""+iVal[x], MouseX, MouseY);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setTitle("Temperature statistics: " + parentTemp);
    }//GEN-LAST:event_formWindowOpened

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        bShowTemp = !bShowTemp;
        if(bShowTemp)
        {
            MouseX = evt.getX();
            MouseY = evt.getY();
            this.repaint();
        }
    }//GEN-LAST:event_formMouseClicked

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        if(bShowTemp)
        {
            MouseX = evt.getX();
            MouseY = evt.getY();
            this.repaint();
        }
    }//GEN-LAST:event_formMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statistik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
