/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysmarthome;

import java.awt.Graphics;

/**
 *
 * @author ktams
 */
public class Statistik extends javax.swing.JFrame {

    public byte[] iVal = null;
    /**
     * Creates new form Statistik
     */
    public Statistik() {
        initComponents();
        this.setResizable(false);
        this.setBounds(50, 50, this.getBounds().width, this.getBounds().height);
    }

    @Override
    public void paint(Graphics g)
    {
        g.drawLine(50, 50, 50, 330);
        g.drawLine(50, 330, 850, 330);
        for( int i = 1; i < 100; i++)
        {
            g.drawLine(50 + 8*i, 325, 50 + 8*i, 335);
        }
        g.drawString("today", 820, 350);
        g.drawString("20", 670, 350);
        g.drawString("40", 510, 350);
        g.drawString("60", 370, 350);
        g.drawString("80", 210, 350);
        g.drawString("100 days ago", 10, 350);
        for( int i = 0; i < 70; i += 5)
        {
            g.drawLine(45, 50 + i*4, 55, 50 + i*4);
        }
        g.drawLine(50, 250, 850, 250);
        g.drawString("0°C", 20, 255);
        g.drawString("-10°C", 10, 295);
        g.drawString("10°C", 15, 215);
        g.drawString("20°C", 15, 175);
        g.drawString("30°C", 15, 135);
        g.drawString("40°C", 15, 95);
        
        if(iVal != null)
        {
            for(int i = 0; i < iVal.length-1; i++)
            {
                int x1 = iVal[iVal.length - 1 -i];
                
                int x2 = iVal[iVal.length - 2 - i];
                
                g.drawLine(850 - i*8, 250 - x1*4, 850 - (i+1)*8, 250 - x2*4);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowOpened

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statistik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
